http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    secure-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: no-referrer
        stsSeconds: 31536000
        forceSTSHeader: true
    rate-limit:
      rateLimit:
        average: 100
        burst: 100
        period: 1m
    login-rate-limit:
      rateLimit:
        average: 5
        burst: 5
        period: 1m
    cors:
      headers:
        accessControlAllowOriginList:
          - "http://app.tasks.localhost"
          - "https://app.tasks.localhost"
        accessControlAllowCredentials: true
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "PATCH"
          - "DELETE"
          - "OPTIONS"
        addVaryHeader: true
    compress:
      compress: {}
  serversTransports:
    default:
      forwardingTimeouts:
        dialTimeout: 5s
        responseHeaderTimeout: 10s
