http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    secure-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: no-referrer
        stsSeconds: 31536000
        forceSTSHeader: true
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
